import * as lp from '../models/learning-path';

const next: lp.ChildLearningPath = {
  priority: lp.Priority.gold,
  label: 'Next',
  description: 'Hybrid static & server rendering for React.',
  url: 'https://nextjs.org/',
  videoUrl: 'https://www.youtube.com/watch?v=IkOVe40Sy0U',
  children: {},
  associations: ['react'],
};
const nuxt: lp.ChildLearningPath = {
  priority: lp.Priority.gold,
  label: 'Nuxt',
  description: 'Hybrid static & server rendering for Vue.',
  url: 'https://nuxtjs.org/',
  videoUrl: 'https://www.youtube.com/watch?v=ltzlhAxJr74',
  children: {},
  associations: ['vue'],
};

const frontend: lp.RootLearningPath = {
  priority: lp.Priority.platinum,
  label: 'Front-end',
  description:
    'With the surge of Rich Web Applications followed by Progressive Web Application, building the user facing side of the Internet has never been more impactful.',
  children: {
    web: {
      priority: lp.Priority.platinum,
      color: 'darkSlateGrey',
      label: 'The Web',
      description:
        'First we had steam power, then we had electricity, now we also have The Internet.',
      url: 'https://www.w3.org/',
      videoUrl: 'https://www.youtube.com/watch?v=J8hzJxb0rpc',
      children: {
        http: {
          priority: lp.Priority.gold,
          description:
            'A client-server protocol which is the foundation of any data exchange on the Web.',
          label: 'HTTP',
          url: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview',
          videoUrl: 'https://www.youtube.com/watch?v=iYM2zFP3Zn0',
          children: {},
        },

        browsers: {
          priority: lp.Priority.gold,
          description:
            'Your main window for accessing information on the World Wide Web.',
          label: 'Browsers',
          url: 'https://en.wikipedia.org/wiki/Web_browser',
          videoUrl: 'https://www.youtube.com/watch?v=QzohDuGk4mM',
          children: {},
        },
        dns: {
          priority: lp.Priority.gold,
          description:
            'Without it you\'d be typing in "172.217.18.78" instead of google.com',
          label: 'DNS',
          url: 'https://www.cloudflare.com/learning/dns/what-is-dns/',
          videoUrl: 'https://www.youtube.com/watch?v=uOfonONtIuk',
          children: {},
        },

        hosting: {
          priority: lp.Priority.gold,
          description: 'Make your website accessible to the world.',
          label: 'hosting',
          url:
            'https://www.website.com/beginnerguide/webhosting/6/1/what-is-web-hosting',
          videoUrl: 'https://www.youtube.com/watch?v=0hGK7qiQ6WA',
          children: {},
        },
      },
    },
    html: {
      priority: lp.Priority.platinum,
      description:
        'In 1989 Tim Berners-Lee created the first website using the Hyper Text Markup Language.',
      color: 'orangeRed',
      label: 'HTML',
      url: 'https://www.w3schools.com/html/html_intro.asp',
      videoUrl: 'https://www.youtube.com/watch?v=UB1O30fR-EE',
      children: {
        semanticHtml: {
          priority: lp.Priority.gold,
          description: 'Meaningful HTML.',
          label: 'Semantic HTML',
          url: 'https://www.w3schools.com/html/html5_semantic_elements.asp',
          videoUrl: 'https://www.youtube.com/watch?v=g2tzEil5TL0',
          children: {},
        },
        formsAndValidation: {
          priority: lp.Priority.gold,
          description:
            'Servers constantly send information to clients, but clients can also send information to servers.',
          label: 'Forms and Validation',
          url: 'https://www.w3schools.com/html/html_forms.asp',
          videoUrl: 'https://www.youtube.com/watch?v=fNcJuPIZ2WE',
          children: {},
        },
        seo: {
          priority: lp.Priority.gold,
          description: 'Want to get your site on the first page of Google?',
          label: 'SEO',
          url: 'https://moz.com/beginners-guide-to-seo',
          videoUrl: 'https://www.youtube.com/watch?v=DvwS7cV9GmQ',
          children: {},
        },
      },
    },
    css: {
      priority: lp.Priority.platinum,
      color: 'mediumBlue',
      label: 'CSS',
      description: 'We all need some style in our lives.',
      url: 'https://www.w3schools.com/css/css_intro.asp',
      videoUrl: 'https://www.youtube.com/watch?v=yfoY53QXEnI',
      children: {
        buildingLayouts: {
          priority: lp.Priority.gold,
          label: 'Building Layouts',
          description:
            'This can be frustrating, but after some time it becomes second nature.',
          url: 'https://www.w3schools.com/css/css_website_layout.asp',
          videoUrl: 'https://www.youtube.com/watch?v=R7gqJkdc5dM',
          children: {
            floats: {
              priority: lp.Priority.gold,
              label: 'Floats',
              description: 'Left or right?',
              url: 'https://www.w3schools.com/cssref/pr_class_float.asp',
              videoUrl: 'https://www.youtube.com/watch?v=VwxGKpvW8Zk',
              children: {},
            },
            positioning: {
              priority: lp.Priority.gold,
              label: 'Positioning',
              description: 'Not everything is static in this world.',
              url: 'https://www.w3schools.com/css/css_positioning.asp',
              videoUrl: 'https://www.youtube.com/watch?v=jx5jmI0UlXU',
              children: {},
            },
            display: {
              priority: lp.Priority.gold,
              label: 'Display',
              description: 'To display or not to display?',
              url: 'https://www.w3schools.com/css/css_display_visibility.asp',
              videoUrl: 'https://www.youtube.com/watch?v=Qf-wVa9y9V4',
              children: {},
            },
            boxModel: {
              priority: lp.Priority.gold,
              label: 'Box Model',
              description: 'Elements can be deceiving.',
              url: 'https://www.w3schools.com/css/css_boxmodel.asp',
              videoUrl: 'https://www.youtube.com/watch?v=rIO5326FgPE',
              children: {},
            },
            cssGrid: {
              priority: lp.Priority.gold,
              label: 'CSS Grid',
              description: 'What can one do with rows and columns?',
              url: 'https://www.w3schools.com/css/css_grid.asp',
              videoUrl: 'https://www.youtube.com/watch?v=jV8B24rSN5o',
              children: {},
            },
            flexBox: {
              priority: lp.Priority.gold,
              label: 'Flex Box',
              description:
                'Nowadays, it may be the most common and easiest way to build great layouts.',
              url: 'https://www.w3schools.com/css/css3_flexbox.asp',
              videoUrl: 'https://www.youtube.com/watch?v=JJSoEo8JSnc',
              children: {},
            },
          },
        },
        responsiveDesign: {
          priority: lp.Priority.gold,
          label: 'Responsive Design',
          description:
            'The majority of people access the internet through a mobile device.',
          url: 'https://www.w3schools.com/css/css_rwd_intro.asp',
          videoUrl: 'https://www.youtube.com/watch?v=srvUrASNj0s',
          children: {},
        },
      },
    },
    javaScript: {
      priority: lp.Priority.platinum,
      color: 'yellow',
      label: 'JavaScript',
      description: 'The first language of the web.',
      url: 'https://www.w3schools.com/js/',
      videoUrl: 'https://www.youtube.com/watch?v=PkZNo7MFNFg',
      children: {
        dom: {
          priority: lp.Priority.gold,
          label: 'DOM',
          description: 'The virtual representation of your web page.',
          url: 'https://www.w3schools.com/js/js_htmldom.asp',
          videoUrl: 'https://www.youtube.com/watch?v=0ik6X4DJKCc',
          children: {},
        },

        dataFetching: {
          priority: lp.Priority.gold,
          label: 'Data Fetching',
          description: "Can't get enough of data.",
          url:
            'https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Fetching_data',
          videoUrl: 'https://www.youtube.com/watch?v=PoRJizFvM7s',
          children: {
            ajax: {
              priority: lp.Priority.gold,
              label: 'AJAX',
              description:
                "To get data from the server, you don't have to fetch a whole new page.",
              url: 'https://www.w3schools.com/js/js_ajax_intro.asp',
              videoUrl: 'https://www.youtube.com/watch?v=82hnvUYY6QA',
              children: {},
            },
            fetchApi: {
              priority: lp.Priority.gold,
              label: 'Fetch API',
              description: 'This will teach you how to fetch, I promise.',
              url: 'https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API',
              videoUrl: 'https://www.youtube.com/watch?v=Oive66jrwBs',
              children: {},
            },
          },
        },
        es6: {
          priority: lp.Priority.gold,
          label: 'ES6',
          description: 'The modern JavaScript.',
          url: 'http://es6-features.org/',
          videoUrl: 'https://www.youtube.com/watch?v=IEf1KAcK6A8',
          children: {
            es6Modules: {
              priority: lp.Priority.gold,
              label: 'ES6 Modules',
              description: "Don't pollute the global scope.",
              url:
                'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules',
              videoUrl: 'https://www.youtube.com/watch?v=cRHQNNcYf6s',
              children: {},
            },
            arrayMethods: {
              priority: lp.Priority.gold,
              label: 'Array methods',
              description: "You'll be using these all the time.",
              url: 'https://www.w3schools.com/jsref/jsref_obj_array.asp',
              videoUrl: 'https://www.youtube.com/watch?v=rRgD1yVwIvE',
              children: {},
            },
            variableDeclaration: {
              priority: lp.Priority.gold,
              label: 'Variable Declaration',
              description: 'Know your scope.',
              url:
                'https://www.freecodecamp.org/news/var-let-and-const-whats-the-difference/',
              videoUrl: 'https://www.youtube.com/watch?v=1mgLWu69ijU',
              children: {},
            },
            promises: {
              priority: lp.Priority.gold,
              label: 'Promises',
              description: 'One of the most beloved JS features.',
              url:
                'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise',
              videoUrl: 'https://www.youtube.com/watch?v=DHvZLI7Db8E',
              children: {},
            },
            templateLiterals: {
              priority: lp.Priority.gold,
              label: 'Template Literals',
              description:
                'Before template string people used the "+" operator.',
              url:
                'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals',
              videoUrl: 'https://www.youtube.com/watch?v=NgF9-pdTDGs',
              children: {},
            },
            restAndSpread: {
              priority: lp.Priority.gold,
              label: 'Rest and Spread',
              description: 'Mix and match.',
              url:
                'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax',
              videoUrl: 'https://www.youtube.com/watch?v=iLx4ma8ZqvQ',
              children: {},
            },
            destructuring: {
              priority: lp.Priority.gold,
              label: 'Destructuring',
              description: 'You better add this word to your dictionary.',
              url:
                'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment',
              videoUrl: 'https://www.youtube.com/watch?v=NIq3qLaHCIs',
              children: {},
            },
          },
        },
      },
    },
    versionControl: {
      priority: lp.Priority.platinum,
      color: 'tomato',
      label: 'Version Control',
      description: 'A game changer.',
      url:
        'https://git-scm.com/book/en/v2/Getting-Started-About-Version-Control',
      videoUrl: 'https://www.youtube.com/watch?v=zbKdDsNNOhg',
      children: {
        git: {
          priority: lp.Priority.platinum,
          label: 'Git',
          description: 'The history of your code in the palm of your hand.',
          url: 'https://git-scm.com/about',
          videoUrl: 'https://www.youtube.com/watch?v=USjZcfj8yxE',
          children: {},
        },
        remoteRepositories: {
          priority: lp.Priority.gold,
          label: 'Remote Repositories',
          description: 'Partying alone is not much fun.',
          url: 'https://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes',
          videoUrl: 'https://www.youtube.com/watch?v=Gg4bLk8cGNo',
          children: {
            github: {
              priority: lp.Priority.platinum,
              label: 'Github',
              description: 'The home of Open Source and many more goodies.',
              url: 'https://guides.github.com/activities/hello-world/',
              videoUrl: 'https://www.youtube.com/watch?v=nhNq2kIvi9s',
              children: {},
            },
            gitLab: {
              priority: lp.Priority.bronze,
              label: 'GitLab',
              description: 'Github is not alone either.',
              url: 'https://docs.gitlab.com/ee/gitlab-basics/',
              videoUrl: 'https://www.youtube.com/watch?v=gbJUasioKiI',
              children: {},
            },
            bitbucket: {
              priority: lp.Priority.bronze,
              label: 'Bitbucket',
              description: "Jira's cousin.",
              url:
                'https://www.atlassian.com/git/tutorials/learn-git-with-bitbucket-cloud',
              videoUrl: 'https://www.youtube.com/watch?v=M44nEyd_5To',
              children: {},
            },
          },
        },
      },
    },
    webSecurity: {
      priority: lp.Priority.platinum,
      color: 'steelBlue',
      label: 'Web Security',
      description: "Without security there wouldn't be the Web",
      url: 'https://developer.mozilla.org/en-US/docs/Web/Security',
      videoUrl: 'https://www.youtube.com/watch?v=wIRVn2dZkaA',
      children: {
        https: {
          priority: lp.Priority.gold,
          label: 'Https',
          description: "Don't let other listen in to your conversations.",
          url: 'https://en.wikipedia.org/wiki/HTTPS',
          videoUrl: 'https://www.youtube.com/watch?v=hExRDVZHhig',
          children: {},
        },
        cors: {
          priority: lp.Priority.gold,
          label: 'CORS',
          description: 'Request resources from other origins.',
          url: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS',
          videoUrl: 'https://www.youtube.com/watch?v=Ka8vG5miErk',
          children: {},
        },
        contentSecurityPolicy: {
          priority: lp.Priority.gold,
          label: 'Content Security Policy ',
          description: 'XSS no more.',
          url: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP',
          videoUrl: 'https://www.youtube.com/watch?v=mr230uotw-Y',
          children: {},
        },
        owaspSecurityRisks: {
          priority: lp.Priority.gold,
          label: 'OWASP Security Risks',
          description: 'Treat it as a checklist for security.',
          url: 'https://owasp.org/www-project-top-ten/',
          videoUrl: 'https://www.youtube.com/watch?v=-7B9Ej4BFgw',
          children: {},
        },
      },
    },
    rest: {
      priority: lp.Priority.platinum,
      color: 'real',
      label: 'REST',
      description: "Knock, knock - Who's there?",
      url: 'https://restfulapi.net/',
      videoUrl: 'https://www.youtube.com/watch?v=Q-BpqyOT3a8',
      children: {},
    },
    packageManagers: {
      priority: lp.Priority.platinum,
      color: 'firebrick',
      label: 'Package Managers',
      description: 'Sharing is caring.',
      url:
        'https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Package_management',
      videoUrl: 'https://www.youtube.com/watch?v=-SaZiADGLHs',
      children: {
        npm: {
          priority: lp.Priority.platinum,
          label: 'NPM',
          description: "Node's de facto package manager.",
          url: 'https://www.w3schools.com/nodejs/nodejs_npm.asp',
          videoUrl: 'https://www.youtube.com/watch?v=jHDhaSSKmB0',
          children: {},
        },
        yarn: {
          priority: lp.Priority.gold,
          label: 'Yarn',
          description: 'A fresh perspective on package managers.',
          url: 'https://yarnpkg.com/getting-started',
          videoUrl: 'https://www.youtube.com/watch?v=g9_6KmiBISk',
          children: {},
        },
      },
    },
    cssArchitecture: {
      priority: lp.Priority.gold,
      color: 'midnightBlue',
      label: 'CSS Architecture',
      description: 'Avoid maintainability headaches.',
      url: 'https://philipwalton.com/articles/css-architecture/',
      videoUrl: 'https://www.youtube.com/watch?v=Nxnp-JLgo5I',
      children: {
        bem: {
          priority: lp.Priority.gold,
          label: 'BEM',
          description: 'Block-Element-Modifier',
          url: 'http://getbem.com/introduction/',
          videoUrl: 'https://www.youtube.com/watch?v=er1JEDuPbZQ',
          children: {},
        },
      },
    },
    cssPreprocessors: {
      priority: lp.Priority.gold,
      color: 'navy',
      label: 'CSS Preprocessors',
      description: 'Ever wanted to get more out of CSS?',
      url: 'https://developer.mozilla.org/en-US/docs/Glossary/CSS_preprocessor',
      videoUrl: 'https://www.youtube.com/watch?v=mAHUT1aXUfQ',
      children: {
        sass: {
          priority: lp.Priority.gold,
          label: 'Sass',
          description: 'Nesting, modules, debugging and more.',
          url: 'https://sass-lang.com/guide',
          videoUrl: 'https://www.youtube.com/watch?v=Zz6eOVaaelI',
          children: {},
        },
        less: {
          priority: lp.Priority.bronze,
          label: 'Less',
          description: 'Leaner Style Sheets',
          url: 'http://lesscss.org/',
          videoUrl: 'https://www.youtube.com/watch?v=YD91G8DdUsw',
          children: {},
        },
      },
    },
    buildTools: {
      priority: lp.Priority.platinum,
      color: 'powderBlue',
      label: 'Build Tools',
      description: 'Be in control of your workflow.',
      url: 'https://survivejs.com/webpack/appendices/comparison/',
      videoUrl: 'https://www.youtube.com/watch?v=rSTR4uET2EA',
      children: {
        linters: {
          priority: lp.Priority.gold,
          label: 'Linters',
          description: 'Avoid shooting yourself in the foot.',
          url: 'https://www.codereadability.com/what-are-javascript-linters/',
          videoUrl: 'https://www.youtube.com/watch?v=bkrapYrmRLc',
          children: {
            eslint: {
              priority: lp.Priority.gold,
              label: 'Eslint',
              description: 'Powerful, fast and flexible.',
              url: 'https://eslint.org/docs/user-guide/getting-started',
              videoUrl: 'https://www.youtube.com/watch?v=qhuFviJn-es',
              children: {},
            },
          },
        },
        prettier: {
          priority: lp.Priority.gold,
          label: 'Prettier',
          description: 'Configurable formatter, but with good defaults.',
          url: 'https://prettier.io/docs/en/index.html',
          videoUrl: 'https://www.youtube.com/watch?v=hPI9UnE4dws',
          children: {},
        },
        npmScripts: {
          priority: lp.Priority.gold,
          label: 'NPM Scripts',
          description: 'Easy and simple.',
          url:
            'https://www.freecodecamp.org/news/introduction-to-npm-scripts-1dbb2ae01633/',
          videoUrl: 'https://www.youtube.com/watch?v=hHt3oVk3XVk',
          children: {},
        },
        moduleBundlers: {
          priority: lp.Priority.gold,
          label: 'Module Bundlers',
          description: 'Having a great many modules is no longer a problem.',
          url:
            'https://www.freecodecamp.org/news/javascript-modules-part-2-module-bundling-5020383cf306/',
          videoUrl: 'https://www.youtube.com/watch?v=OhPUaEuEaXk',
          children: {
            webpack: {
              priority: lp.Priority.gold,
              description: 'The most popular, widespread bundler out there.',
              label: 'Webpack',
              url: 'https://webpack.js.org/guides/getting-started/',
              videoUrl: 'https://www.youtube.com/watch?v=TzdEpgONurw',
              children: {},
            },
            rollup: {
              priority: lp.Priority.silver,
              label: 'Rollup',
              description: 'The bundler that popularized tree-shaking',
              url: 'https://rollupjs.org/guide/en/',
              videoUrl: 'https://www.youtube.com/watch?v=ZGa_a164aeM',
              children: {},
            },
            parcel: {
              priority: lp.Priority.silver,
              label: 'Parcel',
              description: 'Blazing fast with zero configuration.',
              url: 'https://parceljs.org/getting_started.html',
              videoUrl: 'https://www.youtube.com/watch?v=OK6akGZCC88',
              children: {},
            },
          },
        },
      },
    },
    frameworks: {
      priority: lp.Priority.platinum,
      color: 'cyan',
      label: 'frameworks',
      description: 'Say goodbye to JQuery.',
      url: 'https://en.wikipedia.org/wiki/JavaScript_framework',
      videoUrl: 'https://www.youtube.com/watch?v=_P2fGeg9I5o',
      children: {
        react: {
          priority: lp.Priority.platinum,
          label: 'React',
          description: 'Widely popular, functional and declarative.',
          url: 'https://reactjs.org/docs/getting-started.html',
          videoUrl: 'https://www.youtube.com/watch?v=9U3IhLAnSxM',
          children: {
            redux: {
              priority: lp.Priority.gold,
              label: 'Redux',
              description: 'Manage global state, the easy way',
              url: 'https://redux.js.org/introduction/getting-started',
              videoUrl: 'https://www.youtube.com/watch?v=poQXNp9ItL4',
              children: {},
            },
            mobX: {
              priority: lp.Priority.gold,
              description:
                'State management with functional reactive programming.',
              label: 'MobX',
              url: 'https://mobx.js.org/README.html#getting-started',
              videoUrl: 'https://www.youtube.com/watch?v=oQiMXRsO4o4',
              children: {},
            },
          },
        },
        angular: {
          priority: lp.Priority.gold,
          label: 'Angular',
          description: 'A framework in the real sense of the word.',
          url: 'https://angular.io/docs',
          videoUrl: 'https://www.youtube.com/watch?v=Fdf5aTYRW0E',
          children: {
            rxjs: {
              priority: lp.Priority.gold,
              label: 'RxJS',
              description: 'Reactive extensions for JS',
              url: 'https://www.learnrxjs.io/',
              videoUrl: 'https://www.youtube.com/watch?v=PhggNGsSQyg',
              children: {},
            },
            ngrx: {
              priority: lp.Priority.gold,
              label: 'NgRX',
              description:
                'Manage state and collections easily, while isolating side effects.',
              url: 'https://ngrx.io/docs',
              videoUrl: 'https://www.youtube.com/watch?v=f97ICOaekNU',
              children: {},
            },
          },
        },
        vue: {
          priority: lp.Priority.gold,
          label: 'Vue',
          description: 'The best of both worlds.',
          url: 'https://vuejs.org/v2/guide/',
          videoUrl: 'https://www.youtube.com/watch?v=Wy9q22isx3U',
          children: {
            vueX: {
              priority: lp.Priority.gold,
              label: 'VueX',
              description: 'The power of Redux for Vue.',
              url: 'https://vuex.vuejs.org/',
              videoUrl: 'https://www.youtube.com/watch?v=5lVQgZzLMHc',
              children: {},
            },
          },
        },
      },
    },
    cssInJs: {
      priority: lp.Priority.platinum,
      color: 'limeGreen',
      label: 'CSS in JS',
      description: 'CSS and JS unite!',
      url: 'https://medium.com/dailyjs/what-is-actually-css-in-js-f2f529a2757',
      videoUrl: 'youtube.com/watch?v=NMiEREulVLc',
      children: {
        styledComponents: {
          priority: lp.Priority.gold,
          label: 'Styled Components',
          description: 'Styling for the component age.',
          url: 'https://styled-components.com/docs/basics',
          videoUrl: 'https://www.youtube.com/watch?v=3SpAg5tr7Ws',
          children: {},
        },
        cssModules: {
          priority: lp.Priority.gold,
          label: 'CSS Modules',
          description: 'Explicit is better than implicit.',
          url: 'https://github.com/css-modules/css-modules',
          videoUrl: 'https://www.youtube.com/watch?v=pKMWU9OrA2s',
          children: {},
        },
        emotion: {
          priority: lp.Priority.gold,
          label: 'Emotion',
          description: 'The new kid around the block.',
          url: 'https://emotion.sh/docs/introduction',
          videoUrl: 'https://www.youtube.com/watch?v=rKz6cLXhpwA',
          children: {},
        },
        jss: {
          priority: lp.Priority.gold,
          label: 'JSS',
          description: 'Declarative, conflict-free and reusable styles.',
          url: 'https://cssinjs.org/?v=v10.4.0',
          videoUrl: 'https://www.youtube.com/watch?v=pCTXxufGW0k',
          children: {},
        },
      },
    },
    webComponents: {
      priority: lp.Priority.gold,
      color: 'darkOrange',
      label: 'Web Components',
      description: 'Custom components for everybody.',
      url: '',
      videoUrl: '',
      children: {
        htmlTemplates: {
          priority: lp.Priority.gold,
          label: 'HTML Templates',
          description: 'Reusable HTML.',
          url: '',
          videoUrl: '',
          children: {},
        },
        customElements: {
          priority: lp.Priority.gold,
          label: 'Custom Elements',
          description: 'Create your personal HTML tag.',
          url: '',
          videoUrl: '',
          children: {},
        },
      },
    },
    componentLibraries: {
      priority: lp.Priority.platinum,
      color: 'deepSykBlue',
      label: 'Component Libraries',
      description: 'Leverage the power of design systems.',
      url: '',
      videoUrl: '',
      children: {
        materialUi: {
          priority: lp.Priority.gold,
          label: 'Material UI',
          description: 'Material design for your website.',
          url: '',
          videoUrl: '',
          children: {},
        },
        antDesign: {
          priority: lp.Priority.gold,
          label: 'Ant Design',
          description: 'Enterprise grade.',
          url: '',
          videoUrl: '',
          children: {},
        },
        grommet: {
          priority: lp.Priority.gold,
          label: 'Grommet',
          description: 'Mobile first.',
          url: '',
          videoUrl: '',
          children: {},
        },
        reactBootstrap: {
          priority: lp.Priority.gold,
          label: 'React Bootstrap',
          description: 'Bootstrap rebuilt for React.',
          url: '',
          videoUrl: '',
          children: {},
        },
      },
    },
    cssLibraries: {
      priority: lp.Priority.gold,
      color: 'rebeccaPurple',
      label: 'CSS Libraries',
      description: "Don't start from scratch.",
      url: '',
      videoUrl: '',
      children: {
        bootstrap: {
          priority: lp.Priority.gold,
          label: 'Bootstrap',
          description: 'A hugely popular front-end toolkit',
          url: '',
          videoUrl: '',
          children: {},
        },
      },
    },
    testing: {
      priority: lp.Priority.platinum,
      color: 'green',
      label: 'Testing',
      description: 'The proof of your code.',
      url: '',
      videoUrl: '',
      children: {
        jest: {
          priority: lp.Priority.platinum,
          label: 'Jest',
          description: 'Powerful and simple - get started with zero config.',
          url: '',
          videoUrl: '',
          children: {},
        },
        testingLibrary: {
          priority: lp.Priority.platinum,
          label: 'Testing Library',
          description: 'Develop confidence in your app.',
          url: '',
          videoUrl: '',
          children: {},
        },
        cypress: {
          priority: lp.Priority.platinum,
          label: 'Cypress',
          description: 'The web has evolved, finally testing has too.',
          url: '',
          videoUrl: '',
          children: {},
        },
        cucumber: {
          priority: lp.Priority.gold,
          label: 'Cucumber',
          description: 'BDD - Example mapping and TDD.',
          url: '',
          videoUrl: '',
          children: {},
        },
        mochaAndChai: {
          priority: lp.Priority.bronze,
          label: 'Mocha And Chai',
          description: 'The famous test runner and assertion lib duo.',
          url: '',
          videoUrl: '',
          children: {},
        },
      },
    },
    typeCheckers: {
      priority: lp.Priority.platinum,
      color: 'royalBlue',
      label: 'Type Checkers',
      description: 'Streamline your development and make refactoring a breeze.',
      url: '',
      videoUrl: '',
      children: {
        typeScript: {
          priority: lp.Priority.gold,
          label: 'TypeScript',
          description: 'Typed JavScript at scale.',
          url: '',
          videoUrl: '',
          children: {},
        },
      },
    },
    progressiveWebApps: {
      priority: lp.Priority.platinum,
      color: 'indigo',
      label: 'Progressive Web Apps',
      description: 'Websites that took all the right vitamins.',
      url: '',
      videoUrl: '',
      children: {
        serviceWorkers: {
          priority: lp.Priority.platinum,
          label: 'Service Workers',
          description: 'Offline support for your apps and more.',
          url: '',
          videoUrl: '',
          children: {},
        },
        manifest: {
          priority: lp.Priority.platinum,
          label: 'Manifest',
          description: 'Have users install your web app like a native app.',
          url: '',
          videoUrl: '',
          children: {},
        },
        pushNotifications: {
          priority: lp.Priority.gold,
          label: 'Push Notifications',
          description: 'Keep your users engaged.',
          url: '',
          videoUrl: '',
          children: {},
        },
        deviceApis: {
          priority: lp.Priority.gold,
          label: "Device API's",
          description: 'Access to camera, bluetooth and more.',
          url: '',
          videoUrl: '',
          children: {},
        },
        prplPattern: {
          priority: lp.Priority.gold,
          label: 'PRPL Pattern',
          description: 'Push, render, pre-cache, lazy-load.',
          url: '',
          videoUrl: '',
          children: {},
        },
      },
    },
    lighthouse: {
      priority: lp.Priority.platinum,
      color: 'orange',
      label: 'LightHouse',
      description: 'Does your app measure up?',
      url: '',
      videoUrl: '',
      children: {},
    },
    performanceOptimization: {
      priority: lp.Priority.platinum,
      color: 'hotPink',
      label: 'Performance Optimization',
      description: 'Performance can make or break a site.',
      url: '',
      videoUrl: '',
      children: {},
    },
    websockets: {
      priority: lp.Priority.gold,
      color: 'black',
      label: 'Websockets',
      description: 'Real time updates on all of your users devices.',
      url: '',
      videoUrl: '',
      children: {},
    },
    analytics: {
      priority: lp.Priority.platinum,
      color: 'orchid',
      label: 'Analytics',
      description: 'Measure what matters.',
      url: '',
      videoUrl: '',
      children: {
        googleAnalytics: {
          priority: lp.Priority.gold,
          label: 'Google Analytics',
          description: 'The OG Analytics toolkit.',
          url: '',
          videoUrl: '',
          children: {},
        },
        mixPanel: {
          priority: lp.Priority.gold,
          label: 'Mix Panel',
          description: 'The new-gen of analytics.',
          url: '',
          videoUrl: '',
          children: {},
        },
      },
    },
    serverSideRendering: {
      priority: lp.Priority.gold,
      color: 'dimGrey',
      label: 'Server Side Rendering',
      description: 'Achieve great loading speeds, SEO and more.',
      url: '',
      videoUrl: '',
      children: {
        next,
        angularUniversal: {
          priority: lp.Priority.gold,
          label: 'Angular Universal',
          description: 'Hybrid static & server rendering for Angular.',
          url: '',
          videoUrl: '',
          children: {},
          associations: ['angular'],
        },
        nuxt,
      },
    },
    graphql: {
      priority: lp.Priority.gold,
      color: 'deepPink',
      label: 'GraphQL',
      description: "Type safe and developer friendly API's.",
      url: '',
      videoUrl: '',
      children: {
        apollo: {
          priority: lp.Priority.gold,
          label: 'Apollo',
          description: 'GraphQL tooling.',
          url: '',
          videoUrl: '',
          children: {},
        },
        relay: {
          priority: lp.Priority.silver,
          label: 'Relay',
          description: 'GraphQL client for React',
          url: '',
          videoUrl: '',
          children: {},
        },
      },
    },
    staticSiteGenerators: {
      priority: lp.Priority.gold,
      color: 'purple',
      label: 'staticSiteGenerators',
      description: 'Perfect for blogs, documentation, landing pages and more.',
      url: '',
      videoUrl: '',
      children: {
        next,
        gatsby: {
          priority: lp.Priority.gold,
          label: 'Gatsby',
          description: 'Powerful and configurable with over 2000 plugins.',
          url: '',
          videoUrl: '',
          children: {},
        },
        nuxt,
        jekyll: {
          priority: lp.Priority.bronze,
          label: 'Jekyll',
          description:
            'Transform your text or markdown into static websites or blogs.',
          url: '',
          videoUrl: '',
          children: {},
        },
        huge: {
          priority: lp.Priority.bronze,
          label: 'Hugo',
          description: 'Promises speed, flexibility and fun.',
          url: '',
          videoUrl: '',
          children: {},
        },
      },
    },
    mobileApps: {
      priority: lp.Priority.gold,
      color: 'turquoise',
      label: 'Mobile Apps',
      description: 'Building native mobile apps with web technologies.',
      url: '',
      videoUrl: '',
      children: {
        reactNative: {
          priority: lp.Priority.gold,
          label: 'React Native',
          description:
            'Leverage the power or React to build IOS and Android apps',
          url: '',
          videoUrl: '',
          children: {},
        },
        flutter: {
          priority: lp.Priority.silver,
          label: 'Flutter',
          description:
            'Beautiful, natively compiled applications for mobile and more.',
          url: '',
          videoUrl: '',
          children: {},
        },
        ionic: {
          priority: lp.Priority.bronze,
          label: 'Ionic',
          description: 'Mobile UI toolkit for multiple frameworks.',
          url: '',
          videoUrl: '',
          children: {},
        },
      },
    },
    desktopApps: {
      priority: lp.Priority.silver,
      color: 'cadetBlue',
      label: 'Desktop Apps',
      description: 'Building desktop apps with web technologies.',
      url: '',
      videoUrl: '',
      children: {
        electron: {
          priority: lp.Priority.silver,
          label: 'Electron',
          description: 'Cross-platform desktop apps with JS, HTML and CSS.',
          url: '',
          videoUrl: '',
          children: {},
        },
      },
    },
    webAssembly: {
      priority: lp.Priority.gold,
      color: 'darkSlateBlue',
      label: 'Web Assembly',
      description:
        'Portable compilation target for programming languages, enabling deployment on the web.',
      url: '',
      videoUrl: '',
      children: {
        rust: {
          priority: lp.Priority.gold,
          label: 'Rust',
          description:
            'Rust is syntactically similar to C++ and provides memory safety without using garbage collection.',
          url: '',
          videoUrl: '',
          children: {},
        },
        cpp: {
          priority: lp.Priority.silver,
          label: 'C++',
          description:
            'Year after year, one of the 5 programming languages - known for exceptional performance and reliability.',
          url: '',
          videoUrl: '',
          children: {},
        },
      },
    },
  },
};

export default frontend;
